export interface CategoryConfig {
  slug: string;
  label: string;
  description: string;
  mission: string;
  keyEntities: string[];
  pillarTopics: string[];
  primarySources: string[];
  pillBg: string;
  pillText: string;
}

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  native_and_first_nations: {
    slug: "native_and_first_nations",
    label: "Native & First Nations",
    description: "Documented history of Indigenous nations across the full timeline — from pre-Columbian civilizations through the federal treaty era, forced removal policies, the boarding school program, and the ongoing legal framework governing tribal sovereignty. ClownBinge documents the official record: congressional treaty records that were subsequently broken, Bureau of Indian Affairs administrative history, and the Supreme Court decisions that shaped Indigenous rights from Cherokee Nation v. Georgia (1831) through McGirt v. Oklahoma (2020). Coverage includes demographic recovery data, land trust disputes, and the documented gap between federal treaty obligations and federal actions.",
    mission: "To make the primary documentary record of Indigenous history — treaties, court decisions, congressional acts, and demographic research — accessible without editorializing.",
    keyEntities: ["Bureau of Indian Affairs", "Indian Removal Act", "Dawes Act", "Cherokee Nation", "Lakota Nation", "McGirt v. Oklahoma", "Indian Child Welfare Act", "Native American Graves Protection and Repatriation Act"],
    pillarTopics: ["Federal treaty obligations", "Boarding school program (1870s–1970s)", "Tribal sovereignty law", "Land rights and trust disputes", "Demographic recovery"],
    primarySources: ["Congressional treaty records", "Bureau of Indian Affairs documents", "Supreme Court opinions", "Federal commission reports", "Peer-reviewed demographic research"],
    pillBg: "bg-amber-700",
    pillText: "text-white",
  },
  technology: {
    slug: "technology",
    label: "Technology",
    description: "Documented record of technology industry regulatory proceedings, congressional testimony, algorithmic accountability research, and data privacy enforcement actions. Coverage spans FTC antitrust proceedings against major platforms, the documented gap between corporate privacy statements and disclosed data practices, algorithmic content moderation congressional testimony, and the regulatory enforcement record across federal agencies. Every article is built on filed documents: FTC complaints, congressional hearing transcripts, court decisions, and peer-reviewed computer science and policy research from credentialed institutions.",
    mission: "To document what technology companies and regulators have actually stated on the record — not what they claim to believe — using federal filings, congressional testimony, and published research.",
    keyEntities: ["Federal Trade Commission", "U.S. Congress", "Meta", "Google", "Apple", "Amazon", "Microsoft", "NSA", "CISA"],
    pillarTopics: ["Antitrust enforcement", "Data privacy regulation", "Algorithmic accountability", "Surveillance infrastructure", "Congressional testimony record"],
    primarySources: ["FTC filings and complaints", "Congressional testimony transcripts", "Federal court decisions", "Peer-reviewed research", "Corporate disclosure filings"],
    pillBg: "bg-sky-600",
    pillText: "text-white",
  },
  anti_racist_heroes: {
    slug: "anti_racist_heroes",
    label: "Anti-Racist Heroes",
    description: "Documented record of individuals and organizations who resisted racial discrimination through legal challenge, legislative advocacy, civil disobedience, and documented acts of solidarity. ClownBinge covers the primary source record: court filings, congressional testimony, arrest records, legislative histories, and contemporaneous documentation of resistance from Reconstruction through the civil rights era and into the present. Every subject is documented against the historical record — not hagiography, but the verified, sourced account of what they did, what it cost, and what the official record shows.",
    mission: "To document the verified record of anti-racist resistance using court records, legislative history, and primary source archives — making the evidence accessible rather than mythologized.",
    keyEntities: ["NAACP", "SNCC", "Thurgood Marshall", "Fannie Lou Hamer", "Rosa Parks", "Claudette Colvin", "John Lewis", "Ida B. Wells"],
    pillarTopics: ["Legal challenges to segregation", "Voting rights advocacy", "Civil disobedience documentation", "Legislative history of civil rights", "Contemporary resistance record"],
    primarySources: ["Court records and filings", "Congressional testimony", "NAACP archives", "FBI surveillance files", "Contemporaneous news documentation"],
    pillBg: "bg-yellow-400",
    pillText: "text-gray-900",
  },
  money_and_power: {
    slug: "money_and_power",
    label: "Money & Power",
    description: "Documented record of financial industry practices, tax policy, corporate subsidy structures, and the relationship between political donation records and legislative outcomes. ClownBinge builds each article on filed documents: FEC contribution records cross-referenced with voting histories, IRS data on corporate tax rates relative to statutory rates, congressional testimony on subsidy authorization, and federal agency enforcement records against financial institutions. The focus is on the documented gap between stated policy rationale and the documented outcome for working people.",
    mission: "To make the documented relationship between money and political outcomes readable — using FEC filings, IRS data, congressional records, and federal enforcement history.",
    keyEntities: ["Federal Election Commission", "IRS", "SEC", "Federal Reserve", "Treasury Department", "Wall Street", "K Street", "U.S. Chamber of Commerce"],
    pillarTopics: ["Campaign finance and voting records", "Corporate tax enforcement", "Subsidy authorization history", "Financial regulatory enforcement", "Wealth concentration data"],
    primarySources: ["FEC filings", "IRS statistical data", "Congressional voting records", "SEC enforcement actions", "Federal Reserve research"],
    pillBg: "bg-emerald-700",
    pillText: "text-white",
  },
  law_and_justice: {
    slug: "law_and_justice",
    label: "Law & Justice Files",
    description: "Documented record of criminal justice outcomes — sentencing disparity data, prosecutorial conduct, wrongful conviction records, and the gap between constitutional guarantees and system-level outcomes. ClownBinge works from the official record: DOJ statistical reports, court decisions, congressional oversight testimony, inspector general findings, and peer-reviewed criminology research. Coverage includes documented racial disparities in charging and sentencing, civil asset forfeiture data, qualified immunity decisions, and the federal prison system's official record.",
    mission: "To document what the criminal justice system does on the record — not what it claims to do — using official statistics, court decisions, and oversight reports.",
    keyEntities: ["Department of Justice", "Federal Bureau of Prisons", "Supreme Court", "ACLU", "Innocence Project", "U.S. Sentencing Commission"],
    pillarTopics: ["Sentencing disparity research", "Prosecutorial misconduct record", "Wrongful conviction documentation", "Civil rights enforcement", "Prison system data"],
    primarySources: ["DOJ statistical reports", "U.S. Sentencing Commission data", "Federal court decisions", "Inspector general reports", "Peer-reviewed criminology research"],
    pillBg: "bg-red-700",
    pillText: "text-white",
  },
  us_constitution: {
    slug: "us_constitution",
    label: "U.S. Constitution",
    description: "Documented record of constitutional interpretation — Supreme Court decisions, congressional debate records, and the documented evolution of constitutional law from ratification through the present. ClownBinge examines the primary source record: original constitutional convention notes, Federalist Papers, Supreme Court opinions, congressional debates on constitutional amendments, and the academic legal scholarship that tracks how constitutional meaning has shifted across historical contexts. Particular attention is given to the documented gap between originalist claims and historical evidence.",
    mission: "To make constitutional history readable through the primary documents — Supreme Court opinions, founding-era records, and congressional debate transcripts.",
    keyEntities: ["Supreme Court", "Constitutional Convention", "Federalist Papers", "Bill of Rights", "14th Amendment", "Equal Protection Clause", "First Amendment"],
    pillarTopics: ["Supreme Court decision history", "Amendment ratification record", "Originalism and historical evidence", "Civil liberties case law", "Separation of powers doctrine"],
    primarySources: ["Supreme Court opinions", "Constitutional convention records", "Congressional debate transcripts", "Federalist Papers", "Legal scholarship"],
    pillBg: "bg-indigo-700",
    pillText: "text-white",
  },
  women_and_girls: {
    slug: "women_and_girls",
    label: "Women & Girls",
    description: "Documented record of gender policy — reproductive rights legislation, workplace discrimination enforcement data, pay equity research, and the documented gap between legislative intent and measurable outcome. ClownBinge covers the official record: EEOC enforcement data cross-referenced with discrimination complaint outcomes, congressional testimony on reproductive health legislation, court decisions on gender discrimination, and peer-reviewed research on wage gaps across sectors. Every claim is tied to a filed document, published dataset, or court record.",
    mission: "To document gender policy through the official record — EEOC data, court decisions, congressional testimony, and peer-reviewed research — not through assertion.",
    keyEntities: ["EEOC", "Title IX", "Title VII", "Planned Parenthood v. Casey", "Dobbs v. Jackson", "Violence Against Women Act", "Paycheck Fairness Act"],
    pillarTopics: ["Reproductive rights legislation", "Workplace discrimination enforcement", "Pay equity research", "Title IX implementation", "Gender-based violence policy"],
    primarySources: ["EEOC enforcement data", "Congressional testimony", "Federal court decisions", "Peer-reviewed research", "Bureau of Labor Statistics data"],
    pillBg: "bg-rose-600",
    pillText: "text-white",
  },
  us_history: {
    slug: "us_history",
    label: "U.S. History",
    description: "Documented record of American history organized by thematic cluster: the legal mechanisms of dispossession (Dawes Act, California Land Act courts, Tulsa riot exclusion clauses, Bracero Program wage escrow, Sundown Town covenants); Indigenous nations' survival, knowledge systems, and demographic recovery; Black American history from the Great Dismal Swamp Maroon Nation through COINTELPRO; Asian American erasure and arrival; American eugenics and its operational legacy in Nazi Germany; and the primary source record of who built the United States and who paid for it. Every article is sourced from the primary documentary record: National Archives collections, congressional acts, commission reports, Supreme Court decisions, federal census data, and peer-reviewed historical scholarship.",
    mission: "To document American history through the primary sources — National Archives, congressional records, commission reports, court decisions, and peer-reviewed scholarship — organized for depth and topical coherence rather than narrative convenience.",
    keyEntities: [
      "Dawes Act (1887)",
      "Treaty of Guadalupe Hidalgo (1848)",
      "Freedmen's Bureau",
      "COINTELPRO",
      "Tuskegee Syphilis Study",
      "Chinese Exclusion Act (1882)",
      "Executive Order 9066",
      "Indian Adoption Project",
      "Tulsa Race Massacre Commission",
      "Buck v. Bell (1927)",
      "Bracero Program",
      "Great Dismal Swamp Maroon Nation",
      "Bonus Army (1932)",
    ],
    pillarTopics: [
      "Legal instruments of property dispossession — The Ivory Terror Project",
      "Indigenous survival, knowledge, and demographic recovery",
      "Black American history: Reconstruction through COINTELPRO",
      "Asian American history: exclusion, internment, and arrival",
      "American eugenics and scientific racism",
      "Labor history: who built America and who was paid",
    ],
    primarySources: [
      "National Archives (Record Groups 48, 75, 90, 319)",
      "Oklahoma Commission to Study the Tulsa Race Riot (2001)",
      "Freedmen's Bureau Records — 1.5 million pages",
      "FBI COINTELPRO declassified files",
      "2020 U.S. Census Bureau demographic data",
      "Federal Reserve historical economic research",
    ],
    pillBg: "bg-teal-700",
    pillText: "text-white",
  },
  religion: {
    slug: "religion",
    label: "Religion",
    description: "Documented record of religious institutional practices — tax-exempt status data, lobbying expenditure filings, and the documented gap between stated religious principles and institutional behavior. ClownBinge works from the official filing record: IRS Form 990 disclosures, FEC lobbying registrations, court records involving religious institutions, and congressional testimony. Coverage includes the documented history of religious institutions in US public policy, the legal framework governing tax exemption, and specific institutional conduct documented in court proceedings.",
    mission: "To document religious institutional conduct through the filed record — IRS disclosures, court decisions, and congressional testimony — not through theological argument.",
    keyEntities: ["IRS", "FFRF", "Alliance Defending Freedom", "Catholic Church", "Southern Baptist Convention", "LDS Church", "Establishment Clause"],
    pillarTopics: ["Tax exemption compliance", "Lobbying and political expenditures", "Institutional conduct in court records", "Church-state legal history", "Congressional testimony"],
    primarySources: ["IRS Form 990 filings", "FEC lobbying records", "Federal court decisions", "Congressional testimony", "Inspector general reports"],
    pillBg: "bg-violet-700",
    pillText: "text-white",
  },
  investigations: {
    slug: "investigations",
    label: "Investigations",
    description: "Original investigative documentation — systematic examination of public records, financial disclosures, government filings, and official documents to establish documented fact patterns. ClownBinge investigations identify what the assembled record shows when cross-referenced across multiple primary source tiers: government documents, court filings, financial disclosures, and official testimony. Every investigation is reproducible — the primary sources are cited with sufficient specificity that any reader can verify the underlying documents independently.",
    mission: "To produce reproducible investigations where the assembled primary record establishes the documented fact pattern and every source is independently verifiable.",
    keyEntities: ["FOIA", "SEC EDGAR", "Federal Courts PACER", "OpenSecrets", "ProPublica Nonprofit Explorer", "Government Accountability Office"],
    pillarTopics: ["FOIA document analysis", "Financial disclosure cross-referencing", "Government contracting records", "Nonprofit financial documentation", "Pattern analysis across public records"],
    primarySources: ["FOIA-obtained documents", "SEC EDGAR filings", "Federal court records", "Government accountability reports", "Financial disclosure filings"],
    pillBg: "bg-amber-600",
    pillText: "text-white",
  },
  war_and_inhumanity: {
    slug: "war_and_inhumanity",
    label: "War & Inhumanity",
    description: "Documented record of military operations, civilian casualty data, war crimes proceedings, and the gap between official military statements and documented outcomes. ClownBinge works from the primary record: UN reports, military after-action documents obtained through FOIA, international tribunal filings, congressional oversight testimony, and peer-reviewed conflict research. Coverage includes the documented history of US military actions and their outcomes, international humanitarian law proceedings, and the official record of domestic intelligence operations.",
    mission: "To document what war looks like in primary sources — UN reports, tribunal filings, military records, and congressional oversight testimony — rather than official statements.",
    keyEntities: ["UN Human Rights Council", "International Criminal Court", "Pentagon", "CENTCOM", "Senate Armed Services Committee", "Geneva Conventions"],
    pillarTopics: ["Civilian casualty documentation", "International tribunal proceedings", "FOIA military records", "Congressional oversight of armed forces", "Humanitarian law enforcement"],
    primarySources: ["UN reports", "FOIA military records", "International tribunal filings", "Congressional oversight testimony", "Peer-reviewed conflict research"],
    pillBg: "bg-orange-700",
    pillText: "text-white",
  },
  health_and_healing: {
    slug: "health_and_healing",
    label: "Health & Healing",
    description: "Documented record of US health policy — drug pricing mechanisms, FDA approval processes, public health interventions, pharmaceutical industry practices, and the documented outcomes of medical and policy decisions. ClownBinge works from the official record: FDA filings and approval data, congressional testimony on drug pricing, CMS reimbursement data, peer-reviewed clinical research, and congressional budget analysis. Particular attention is given to the documented gap between pharmaceutical company statements and their disclosed trial data.",
    mission: "To document health policy through the official record — FDA filings, congressional testimony, peer-reviewed research, and CMS data — making the primary sources accessible.",
    keyEntities: ["FDA", "CDC", "NIH", "CMS", "HHS", "PhRMA", "WHO", "Senate HELP Committee"],
    pillarTopics: ["Drug pricing and patent policy", "FDA approval documentation", "Public health intervention data", "Pharmaceutical industry disclosures", "Health insurance coverage data"],
    primarySources: ["FDA filings and approval records", "Congressional testimony", "Peer-reviewed clinical research", "CMS reimbursement data", "Congressional Budget Office analysis"],
    pillBg: "bg-green-700",
    pillText: "text-white",
  },
  censorship: {
    slug: "censorship",
    label: "Censorship",
    description: "Documented record of press freedom, government information control, content moderation policy, and the suppression of journalism. ClownBinge covers the primary source record: court decisions on prior restraint and shield laws, congressional testimony on government information classification, Reporters Without Borders and CPJ documentation of journalist targeting, and FCC enforcement records. Coverage includes the documented history of government classification decisions and the legal framework governing press freedom in the United States.",
    mission: "To document press freedom and censorship through the official record — court decisions, congressional testimony, and international press freedom documentation.",
    keyEntities: ["First Amendment", "FCC", "Espionage Act", "Reporters Without Borders", "Committee to Protect Journalists", "Pentagon Papers", "FISA Court"],
    pillarTopics: ["Prior restraint case law", "Government classification history", "Shield law legislation", "Journalist targeting documentation", "Content moderation regulation"],
    primarySources: ["Federal court decisions", "Congressional testimony", "CPJ and RSF documentation", "FCC enforcement records", "FOIA classification decisions"],
    pillBg: "bg-zinc-700",
    pillText: "text-white",
  },
  global_south: {
    slug: "global_south",
    label: "Global South",
    description: "Documented record of international development policy — World Bank and IMF structural adjustment programs, colonial-era resource extraction, sovereign debt structures, and the documented outcomes of international financial interventions in the developing world. ClownBinge works from the primary institutional record: World Bank project appraisal documents, IMF country program agreements, UN development data, and peer-reviewed development economics research. Coverage examines the documented gap between development institution stated objectives and measurable country outcomes.",
    mission: "To document international development policy through institutional primary sources — World Bank filings, IMF agreements, UN data, and peer-reviewed research.",
    keyEntities: ["World Bank", "IMF", "WTO", "USAID", "UN Development Programme", "Structural Adjustment Programs", "Bretton Woods institutions"],
    pillarTopics: ["Structural adjustment program outcomes", "Sovereign debt and conditionality", "Colonial resource extraction documentation", "Development institution accountability", "Trade agreement impact data"],
    primarySources: ["World Bank project documents", "IMF country agreements", "UN development data", "Peer-reviewed economics research", "Congressional appropriations records"],
    pillBg: "bg-cyan-700",
    pillText: "text-white",
  },
  how_it_works: {
    slug: "how_it_works",
    label: "How It Works",
    description: "Documented explanations of institutional structures — how legislation becomes law, how regulatory agencies function, how federal appropriations work, and how the documented federal processes operate in practice versus in stated intent. ClownBinge builds these explainers on primary sources: the Constitution, congressional procedural rules, agency enabling statutes, and the official procedural record. These articles are designed to make the machinery of government legible using its own documentation rather than simplified description.",
    mission: "To explain institutional structures using primary documents — enabling statutes, procedural rules, and the official record — not simplified description.",
    keyEntities: ["U.S. Congress", "Congressional Research Service", "Office of Management and Budget", "Administrative Procedure Act", "APA", "Federal Register"],
    pillarTopics: ["Legislative process documentation", "Regulatory rulemaking procedure", "Federal budget process", "Agency structure and authority", "Administrative law basics"],
    primarySources: ["Congressional procedural rules", "Agency enabling statutes", "Federal Register rulemaking records", "Congressional Research Service reports", "Government Accountability Office reports"],
    pillBg: "bg-slate-600",
    pillText: "text-white",
  },
  nerd_out: {
    slug: "nerd_out",
    label: "NerdOut / Academic",
    description: "Peer-reviewed and scholarly deep dives into documented historical, scientific, and legal records — structured for readers who want the full primary source analysis. NerdOut articles on ClownBinge are written at academic depth: citing specific study DOIs, court opinion paragraph numbers, and legislative history pages. Coverage includes quantitative analysis of official datasets, legal history tracing doctrines to their source documents, and examination of peer-reviewed research across relevant disciplines. These are long-form, citation-dense, and built for readers who want the evidence rather than the summary.",
    mission: "To produce citation-dense scholarly analysis using peer-reviewed research, complete legal history, and full primary source documentation for readers who want depth.",
    keyEntities: ["JSTOR", "PubMed", "HeinOnline", "Google Scholar", "National Archives", "Congressional Research Service"],
    pillarTopics: ["Peer-reviewed research synthesis", "Legal doctrine history", "Legislative history analysis", "Quantitative dataset examination", "Interdisciplinary scholarship"],
    primarySources: ["Peer-reviewed journals", "Law review articles", "Congressional Research Service reports", "National Archives records", "Official statistical datasets"],
    pillBg: "bg-fuchsia-900",
    pillText: "text-white",
  },
  disarming_hate: {
    slug: "disarming_hate",
    label: "Disarming Hate",
    description: "Documented record of hate groups, hate crimes, and extremist organizations — FBI statistics, federal court records, congressional testimony, and the documented relationship between extremist ideology and violence. ClownBinge works from the official record: FBI hate crime statistics, federal prosecution records, DHS threat assessment reports, congressional testimony on domestic terrorism, and SPLC Intelligence Report documentation. Every organization covered is documented through filed court records, official law enforcement reports, or congressional testimony — not through assertion.",
    mission: "To document hate crime and extremism through the official record — FBI statistics, federal court filings, and congressional testimony — not through assertion.",
    keyEntities: ["FBI", "DHS", "SPLC", "ADL", "Senate Judiciary Committee", "Domestic terrorism statutes", "Matthew Shepard Act"],
    pillarTopics: ["FBI hate crime statistics", "Federal extremism prosecutions", "Domestic terrorism legislative history", "Extremist organization documentation", "Threat assessment records"],
    primarySources: ["FBI hate crime reports", "Federal court records", "DHS threat assessments", "Congressional testimony", "SPLC Intelligence Report"],
    pillBg: "bg-rose-900",
    pillText: "text-white",
  },
  reasons_pen: {
    slug: "reasons_pen",
    label: "Reason's Pen",
    description: "The Reason's Pen is a rare, explicitly authored ClownBinge article category written exclusively by the platform founder. It publishes infrequently and deliberately. Every Reason's Pen piece is a long read by definition. It maintains all CB sourcing standards — Tier One primary documentation, falsifiable claims, verified evidence, three-tier source hierarchy — while departing from CB Dry Rationalism in one named and deliberate respect: it makes no pretense at Eurocentric objectivity. The Reason's Pen carries a documented editorial posture, not an undisclosed one. Every piece includes the mandatory footer disclosing this distinction.",
    mission: "To document the intersection of systemic power and lived experience through the founder's voice, under full CB sourcing standards, with the editorial posture named and disclosed rather than hidden.",
    keyEntities: ["Metricadia-Research LLC", "ClownBinge Editorial Board", "CB Editorial Policy"],
    pillarTopics: ["Systemic analysis", "Institutional power documentation", "Founder's editorial voice", "Primary-source grounded perspective"],
    primarySources: ["Tier One primary documentation", "Peer-reviewed scholarship", "Official government records", "Court decisions and legal filings"],
    pillBg: "bg-[#3D1A00]",
    pillText: "text-white",
  },
  self_owned: {
    slug: "self_owned",
    label: "Self-Owned",
    description: "Documented record of public figures contradicting their own prior statements, votes, and official positions — established exclusively through primary sources. Self-Owned articles on ClownBinge build each contradiction from the documentary record: congressional voting records, official transcripts, press statements entered into the Congressional Record, and publicly filed documents. No interpretation is required: the subject's own documented record is the instrument of contradiction. Every article carries a Self-Own Score (1–10) calibrated to the severity and breadth of the documented gap.",
    mission: "To document public figure contradictions using only their own primary source record — votes, official statements, and filed documents — without editorial interpretation.",
    keyEntities: ["Congressional Record", "GovTrack", "VoteSmart", "C-SPAN", "FEC", "OpenSecrets"],
    pillarTopics: ["Congressional voting record contradictions", "Official statement vs. recorded action", "Campaign promise vs. legislative record", "Regulatory capture documentation", "Self-Own Score methodology"],
    primarySources: ["Congressional voting records", "Official press releases", "Congressional Record transcripts", "C-SPAN video documentation", "FEC filings"],
    pillBg: "bg-primary",
    pillText: "text-white",
  },
};

export function getCategoryConfig(slug: string): CategoryConfig | undefined {
  return CATEGORY_CONFIG[slug];
}

export const ALL_CATEGORIES = Object.values(CATEGORY_CONFIG);
