import pg from '/home/runner/workspace/node_modules/.pnpm/pg@8.20.0/node_modules/pg/lib/index.js';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const body = `<p data-speakable-lede class="cb-lede">The Reverend Jim Jones told his congregation that faith in his system would protect them. He told them the abundance would flow downward from his authority to their lives. He told them that doubt was the enemy of prosperity and that the critics were motivated by malice. He was wrong on all three counts. Trickle-down economics told the American working class the same things using different vocabulary. Faith in tax reduction at the top would produce wage growth at the bottom. Skeptics were socialists. The data would eventually prove the theorists right. The data never did.</p>

<h2>The Theological Architecture of Supply-Side Economics</h2>

<p>The Laffer Curve — the foundational document of supply-side economics — was drawn on a napkin at a Washington restaurant in 1974. Arthur Laffer, an economist at the University of Chicago, sketched a curve for Dick Cheney and Donald Rumsfeld suggesting that at some rate of taxation above zero and below one hundred percent, a reduction in tax rates would increase total government revenue by stimulating economic activity. The curve itself is mathematically uncontroversial at its extremes. A zero percent tax rate produces zero revenue. A one hundred percent tax rate produces approximately zero revenue because no rational actor works for nothing. The theological leap — the one that became the operational premise of American fiscal policy for four decades — was the claim that the United States was operating on the downward slope of that curve, and that substantial reductions in top marginal rates would produce revenue increases, wage growth, and broad economic expansion. <a href="#cite-1" class="cb-factoid" data-title="Laffer, A. B. (2004). The Laffer Curve: Past, Present, and Future. Heritage Foundation Backgrounder No. 1765." data-summary="Laffer's own retrospective account of the Laffer Curve describes the 1974 dinner meeting with Donald Rumsfeld and Dick Cheney where the curve was sketched. Laffer acknowledges the curve is a theoretical construct and that identifying the revenue-maximizing point requires empirical evidence the original formulation did not provide. He concedes the curve does not specify where any given country sits on it at any given moment.">Laffer's own retrospective account of the curve acknowledges it is a theoretical construct whose revenue-maximizing point requires empirical identification.</a> The Reagan administration did not wait for that identification. It acted on faith. That is the definition of a religious posture, not a scientific one.</p>

<p>The internal logic of the supply-side framework became self-sealing in the way that all closed belief systems eventually do. When tax cuts produced the promised growth, they were cited as proof. When they produced deficits and wage stagnation, the explanation was that the cuts had not been large enough, had been offset by spending, or would require additional time before the promised benefits materialized. This unfalsifiability is the structural tell. A theory that can explain every outcome, including the outcomes that contradict its predictions, has ceased to function as a theory. It has become a doctrine. Bruce Bartlett, who served in the Reagan White House and later as a Treasury official under the first Bush administration, reached precisely this conclusion. <a href="#cite-2" class="cb-factoid" data-title="Bartlett, B. (2012). The Benefit and the Burden: Tax Reform — Why We Need It and What It Will Take. Simon and Schuster." data-summary="Bartlett, a former Reagan administration economist and Treasury official under Bush (41), argues that supply-side economics in its original formulation was a legitimate policy response to the extremely high marginal rates of the 1970s, but that it had been transformed into an unfalsifiable ideology in which tax cuts were held to be beneficial under all circumstances regardless of the prevailing rate structure. Bartlett contends the original theoretical basis does not support the broader doctrine that developed from it, and that the doctrine's persistence required ignoring contradicting evidence.">Bartlett's 2012 assessment was that the original supply-side argument was a defensible response to the seventy percent marginal rates of the late 1970s but had since evolved into an unfalsifiable belief system in which tax reduction was assumed to be beneficial under any rate structure and any economic conditions regardless of the evidence.</a> An unfalsifiable belief system is not economics. It is theology dressed in econometric language.</p>

<h2>The Tax Record: Reagan, Bush, and the Debt Arithmetic</h2>

<p>The Economic Recovery Tax Act of 1981 reduced the top marginal federal income tax rate from 70 percent to 50 percent. The Tax Reform Act of 1986 reduced it further to 28 percent. The theory predicted that these reductions would generate sufficient economic growth to offset lost revenue, producing what the supply-siders called a "revenue-neutral" or even "revenue-positive" outcome through the Laffer mechanism. The Congressional Budget Office tracked the results in real time without partisan adjustment. <a href="#cite-3" class="cb-factoid" data-title="Congressional Budget Office. (1990). The Economic and Budget Outlook: Fiscal Years 1991-1995. U.S. Congress." data-summary="CBO projections and retrospective analysis from 1990 document the trajectory of federal revenues and debt accumulation during the Reagan administration. Federal revenues fell as a share of GDP from 19.6 percent in 1981 to 17.3 percent in 1984, before recovering partially. The national debt grew from approximately $994 billion in 1981 to $2.9 trillion by 1989, a tripling of total federal indebtedness during the administration that promised revenue growth through tax reduction.">Federal revenues fell as a share of GDP from 19.6 percent in 1981 to 17.3 percent in 1984, before partially recovering.</a> The national debt, which stood at approximately $994 billion when Reagan took office, exceeded $2.9 trillion when he left. The debt did not triple because of a recession. It tripled during a period of economic expansion. It tripled because the revenue that was supposed to materialize through supply-side stimulus did not materialize at the rates the theory required. The gap was financed by borrowing. The cost of that borrowing was assigned to future taxpayers, the majority of whom would not be in the top marginal bracket that received the rate reduction.</p>

<p>The pattern repeated with near-identical mechanics under the second Bush administration. The Economic Growth and Tax Relief Reconciliation Act of 2001 and the Jobs and Growth Tax Relief Reconciliation Act of 2003 reduced the top marginal rate to 35 percent and created preferential rates for capital gains and dividends. The administration projected that the cuts would pay for themselves through accelerated investment and hiring. The CBO projected the opposite and was correct. The cuts added an estimated $1.7 trillion to the national debt over their first decade, a figure that excludes the interest costs of financing that additional debt. Net job creation across the Bush administration's eight years reached 1.08 million nonfarm payroll positions, the weakest two-term record in the modern BLS tracking period. The Great Recession that began in December 2007 was not an external shock disconnected from the preceding fiscal and regulatory environment. It was the terminal expression of a financial architecture that the tax and deregulatory framework of that decade had encouraged and sustained.</p>

<h2>Comparing Administrations: What the GDP Data Shows</h2>

<p>The Bureau of Economic Analysis publishes quarterly real GDP growth data with consistent methodology across administrations. The Bureau of Labor Statistics publishes monthly nonfarm payroll employment figures under the same methodological framework. These are not partisan sources. They are the federal government's own statistical apparatus, maintained by career economists across administrations of both parties, and subject to revision procedures that are themselves documented and transparent. <a href="#cite-4" class="cb-factoid" data-title="Bureau of Economic Analysis. (2024). National Income and Product Accounts: Real Gross Domestic Product. U.S. Department of Commerce." data-summary="BEA data tracking annualized real GDP growth by quarter from 1947 forward. Analysis by administration shows Democratic administrations averaging approximately 4.4 percent real GDP growth annually versus approximately 2.5 percent for Republican administrations in the post-WWII period. This gap persists across multiple methodological approaches including analyses that adjust for the economic conditions inherited at the start of each term.">Across the post-World War II period, Democratic administrations have averaged approximately 4.4 percent real GDP growth annually versus approximately 2.5 percent for Republican administrations.</a> This is not a one-cycle finding produced by a single anomalous presidency. It persists across the Kennedy, Johnson, Carter, Clinton, and Obama years, and it persists when the analysis excludes years immediately following administrations that inherited acute crises. The gap narrows but does not reverse when adjusted for the economic conditions each administration inherited at inauguration.</p>

<p>Employment data tells a parallel story with the same directional finding. <a href="#cite-5" class="cb-factoid" data-title="Bureau of Labor Statistics. (2024). Current Employment Statistics: Total Nonfarm Payroll Employment. U.S. Department of Labor." data-summary="BLS nonfarm payroll employment data tracks monthly job creation from 1939 forward. By administration in the post-WWII period, Democratic administrations have created an average of approximately 1.8 million net new jobs per year versus approximately 1.0 million per year under Republican administrations. The disparity is largest during the Reagan, Bush (43), and Trump administrations, each of which ended with significantly weaker job creation records than the Democratic administrations preceding or following them.">Under Clinton, the United States added approximately 22.9 million nonfarm payroll jobs across eight years, an average of 2.9 million per year.</a> Under Obama, 11.6 million jobs were added across eight years, with the first year representing the trough of an inherited financial crisis that destroyed 8.7 million jobs. Under Bush (43), the net job creation across eight years was 1.08 million. Under Trump, the administration ended with a net negative job figure driven by the pandemic, though the structural pre-pandemic employment trajectory was already decelerating relative to the late Obama period by early 2020. The BLS data does not speculate about causation. It counts employment. The counts are what they are.</p>

<h2>Wages, Inequality, and the Distributional Failure</h2>

<p>The foundational promise of trickle-down economics was not simply aggregate growth. The specific mechanism was distributional. Growth stimulated at the top would, through investment, hiring, and the natural dynamics of a tightening labor market, produce wage and income gains across the entire income distribution. Workers at the bottom would benefit from the prosperity created at the top. Thomas Piketty and Emmanuel Saez, using Internal Revenue Service records extending back to 1913 and updated through the present, documented what actually happened to the income distribution during the trickle-down era. <a href="#cite-6" class="cb-factoid" data-title="Piketty, T., and Saez, E. (2003). Income Inequality in the United States, 1913-1998. Quarterly Journal of Economics, 118(1), 1-41. Updated series available through 2023." data-summary="Piketty and Saez constructed income distribution data from IRS records covering 1913 through 1998, with the series subsequently updated through the present. Their analysis shows the income share of the top 1 percent fell from roughly 20 percent in the 1920s to approximately 10 percent during the 1950s through 1970s, then rose sharply beginning in 1981, reaching approximately 23 percent by 2007. The reversal is chronologically coincident with the implementation of supply-side tax policy and persists across multiple extensions and replications of the original analysis.">The income share of the top one percent fell from approximately twenty percent in the late 1920s to approximately ten percent by the mid-1970s, then reversed sharply beginning in 1981.</a> By 2007, the top one percent was capturing twenty-three percent of total pre-tax income. The reversal was not gradual. It was chronologically coincident with the implementation of supply-side tax policy, and it accelerated during each subsequent round of upper-bracket rate reductions.</p>

<p>The Economic Policy Institute's longitudinal wage analysis, drawing on BLS and Census Bureau microdata, shows that real wages for workers in the bottom twenty percent of the income distribution grew by less than three percent in total between 1979 and 2021 — a period spanning more than four decades and multiple economic expansions. Workers in the top five percent of the distribution saw real wage growth exceeding sixty percent across the same period. <a href="#cite-7" class="cb-factoid" data-title="Economic Policy Institute. (2021). The State of Working America Wages 2021. Economic Policy Institute." data-summary="EPI's longitudinal wage analysis drawing on BLS and Census Bureau data documents real wage growth by income percentile from 1979 to 2021. Bottom-quintile workers experienced less than 3 percent total real wage growth over the four-decade period while workers in the top quintile saw gains exceeding 50 percent. EPI attributes the disparity to a combination of factors including union decline accelerated by policy choices, minimum wage stagnation in real terms, and tax and regulatory policy changes that began in the early 1980s.">This distributional outcome is the opposite of what trickle-down economics predicted.</a> The framework predicted that growth stimulated at the top would generate labor market tightening that would bid up wages at the bottom. Forty-three years of data from the government's own wage surveys suggests this mechanism either does not operate as theorized, operates on a timescale that renders it useless as policy, or does not operate at all. None of these possibilities supports the claim that supply-side tax policy produces broad prosperity.</p>

<h2>The Kansas Experiment: A Controlled Test</h2>

<p>In 2012, Kansas Governor Sam Brownback signed what he explicitly and publicly described as a "real live experiment" in supply-side economics. The Kansas legislature eliminated income taxes on approximately 330,000 business owners who filed as pass-through entities, reduced individual income tax rates across all brackets, and projected that the resulting economic acceleration would generate sufficient revenue to offset the cuts within a defined projection window. Arthur Laffer personally endorsed the Kansas plan and predicted it would produce economic transformation that would make Kansas "the Mecca of business activity." The Kansas experiment was as close to a controlled empirical test as fiscal policy produces in a democratic system. It ran for five years before the Republican-controlled state legislature voted to reverse it in 2017.</p>

<p>The results during those five years were the following: Kansas job growth consistently underperformed neighboring states that had not implemented comparable cuts. <a href="#cite-8" class="cb-factoid" data-title="Center on Budget and Policy Priorities. (2017). Kansas Lawmakers End Failed Tax Experiment. Center on Budget and Policy Priorities." data-summary="CBPP analysis drawing on Kansas Department of Revenue data, BLS state employment statistics, and Kansas Legislative Research Department fiscal notes documents the outcomes of the Brownback tax experiment from 2012 through 2017. Kansas job growth lagged national averages in four of the five implementation years. State revenues fell so far short of projections that Kansas was forced to draw down its rainy day fund, defer pension payments, reduce K-12 education funding, and cut services to disabled residents. The Republican-controlled legislature reversed the cuts by a veto-proof supermajority in 2017, explicitly citing fiscal failure.">Kansas GDP growth lagged behind national averages in four of the five years following implementation.</a> State revenues fell so far short of projections that Kansas was forced to draw down its rainy day fund, defer payments to the state pension system, reduce funding for public schools below levels the state constitution required, and cut services to disabled residents who depended on state programs. The Republican-controlled legislature voted to override Brownback's veto and restore income taxes in 2017 by a veto-proof supermajority. The experiment produced a finding. The finding contradicted the theory. The contradiction was decisive enough to produce bipartisan legislative reversal in a state with a Republican supermajority. That is the supply-side Laffer mechanism receiving a direct empirical test and failing it in front of a legislature that had originally endorsed the theory.</p>

<h2>The Tax Cuts and Jobs Act: The Most Recent Data</h2>

<p>The Tax Cuts and Jobs Act of 2017 reduced the corporate income tax rate from 35 percent to 21 percent, the largest single reduction in corporate rates in American history. Administration officials projected wage growth of $4,000 to $9,000 per worker annually through increased business investment, domestic hiring incentives, and repatriation of profits held offshore. Treasury Secretary Steven Mnuchin stated publicly that the tax cuts would pay for themselves through growth. The CBO's independent analysis and the Treasury Department's own Office of Tax Analysis both projected that the cuts would add between $1 trillion and $1.9 trillion to the national debt over ten years, even after accounting for dynamic growth effects. <a href="#cite-9" class="cb-factoid" data-title="Congressional Budget Office. (2018). The Budget and Economic Outlook: 2018 to 2028. U.S. Congress." data-summary="CBO ten-year budget and economic projections following TCJA passage show projected revenue losses exceeding $1.5 trillion over the 2018-2027 window under conventional scoring, with partial offset from projected growth effects reducing the net estimate to approximately $1.27 trillion. The report notes that corporate investment increased in 2018 before decelerating to pre-TCJA trend rates, and that projected wage growth did not materialize at the administration's forecast rates in the subsequent years of available data.">The CBO's post-TCJA tracking showed corporate investment rose in 2018 before decelerating to rates consistent with pre-TCJA trends.</a> The promised wage gains did not materialize at the administration's forecast magnitudes. What did materialize was a record level of corporate share buybacks. Companies returned $806 billion to shareholders through buybacks in 2018, the year following the rate reduction. Share buybacks are not investment in productive capacity, equipment, or labor. They are a mechanism for transferring capital to existing shareholders. The mechanism the theory said would generate worker wage growth directed the capital to a different destination.</p>

<h2>The Federal Reserve Distributional Accounts</h2>

<p>The Federal Reserve's Distributional Financial Accounts track household wealth by income and wealth percentile on a quarterly basis using a consistent methodology. The data is maintained by the Federal Reserve Board's staff economists and is publicly available in full. <a href="#cite-10" class="cb-factoid" data-title="Board of Governors of the Federal Reserve System. (2023). Distributional Financial Accounts: Distribution of Household Wealth in the U.S. Federal Reserve Board." data-summary="The Federal Reserve's Distributional Financial Accounts track household wealth by wealth percentile quarterly from 1989 forward. As of Q3 2023, the top 1 percent of wealth holders controlled approximately 30.5 percent of total household wealth, while the bottom 50 percent of households controlled approximately 2.5 percent of total household wealth. The wealth share of the top 1 percent has increased from approximately 23 percent in 1989 to its current level, with the trajectory steepening during periods of capital-gains-favorable tax treatment.">As of 2023, the top one percent of wealth holders control approximately 30.5 percent of total household wealth, up from approximately 23 percent in 1989.</a> The bottom fifty percent of American households control approximately 2.5 percent of total wealth. The distance between these numbers is the empirical record of the distributional mechanism that supply-side economics predicted would operate in the opposite direction. The wealth was supposed to flow down. The Federal Reserve's quarterly tracking of where it actually went shows it flowing up with consistent efficiency across every administration that implemented upper-bracket rate reductions.</p>

<h2>The Democratic Record: The Complications That Do Not Change the Direction</h2>

<p>The empirical record of Democratic administrations does not constitute a simple or unqualified rebuttal to supply-side claims. Carter presided over stagflation that the prevailing Keynesian consensus framework failed to adequately address, and the Federal Reserve's 1979 rate shock under Paul Volcker, which broke the inflationary cycle, was not a Democratic policy initiative. Obama inherited the largest financial crisis since 1929, and the pace of recovery — while statistically consistent — was slower than historical recoveries from comparably deep recessions, in part because fiscal stimulus was reduced prematurely under congressional pressure. Clinton's balanced budget era and the associated growth coincided with a technology investment boom that was substantially independent of marginal tax rates. The relationship between presidential administration and economic outcome involves a lag structure. Policies take time to produce measurable effects. Administrations inherit the conditions their predecessors created. These complications are methodologically real and the empirical record should be read with them in view.</p>

<p>What the complications do not change is the directional finding. Across the consistent, methodologically stable data series maintained by the Bureau of Economic Analysis and the Bureau of Labor Statistics, economic performance measured by real GDP growth, net job creation, and income gains for middle and lower quintile workers has outperformed under Democratic administrations by margins that survive statistical scrutiny and have been documented in peer-reviewed economic literature by researchers with no Democratic party affiliation. The trickle-down mechanism — the specific claim that growth stimulated at the top produces broad prosperity through a definable transmission mechanism — has not been validated by forty-three years of data from the policy's own proponents' preferred government agencies. The mechanism that was promised has not been observed at the scale the theory requires. This is the finding. The finding does not require belief. It requires reading the BEA tables and the BLS payroll data and the Federal Reserve distributional accounts that the federal government has been publishing continuously for decades.</p>

<h2>The Record Stands</h2>

<p>Jim Jones was not wrong because he was cruel, though he was. He was wrong because his claims about how his system worked were empirically false, and the people who paid the cost of that falseness were the people at the bottom of the hierarchy who had placed their faith in the promised flow from above. The analogy to supply-side economics does not require that its architects were malicious. It requires only that the central claim — that prosperity flows downward from concentrated wealth when tax policy facilitates that concentration — was not supported by the evidence available when the policy was designed, was contradicted by the evidence that accumulated as it ran, was directly falsified by a state-level experiment its own advocates designed and endorsed, and remains contradicted by the data available today. The BEA tables are public. The BLS payroll data is public. The Federal Reserve distributional accounts are public. The Kansas Department of Revenue published its own revenue shortfall figures. The Congressional Budget Office scored each major tax legislation package against the administration's projections and the administration's projections were wrong in the same direction every time. The record does not require interpretation. It requires reading.</p>`;

const verifiedSource = `Laffer, A. B. (2004) :: Laffer, A. B. (2004). The Laffer curve: Past, present, and future. Heritage Foundation Backgrounder, 1765. The Heritage Foundation.; Bartlett (2012) :: Bartlett, B. (2012). The benefit and the burden: Tax reform — why we need it and what it will take. Simon and Schuster.; Congressional Budget Office (1990) :: Congressional Budget Office. (1990). The economic and budget outlook: Fiscal years 1991-1995. U.S. Congress.; Bureau of Economic Analysis (2024) :: Bureau of Economic Analysis. (2024). National income and product accounts: Real gross domestic product. U.S. Department of Commerce.; Bureau of Labor Statistics (2024) :: Bureau of Labor Statistics. (2024). Current employment statistics: Total nonfarm payroll employment. U.S. Department of Labor.; Piketty and Saez (2003) :: Piketty, T., and Saez, E. (2003). Income inequality in the United States, 1913-1998. Quarterly Journal of Economics, 118(1), 1-41.; Economic Policy Institute (2021) :: Economic Policy Institute. (2021). The state of working America wages 2021. Economic Policy Institute.; Center on Budget and Policy Priorities (2017) :: Center on Budget and Policy Priorities. (2017). Kansas lawmakers end failed tax experiment. Center on Budget and Policy Priorities.; Congressional Budget Office (2018) :: Congressional Budget Office. (2018). The budget and economic outlook: 2018 to 2028. U.S. Congress.; Board of Governors of the Federal Reserve System (2023) :: Board of Governors of the Federal Reserve System. (2023). Distributional financial accounts: Distribution of household wealth in the U.S. Federal Reserve Board.`;

const result = await pool.query(
  `INSERT INTO posts (
    case_number, title, slug, teaser, body, category, verified_source,
    has_video, tags, status, published_at,
    view_count, share_count, user_submitted, pinned, staff_pick, locked, nerd_accessible
  ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
  RETURNING case_number`,
  [
    'CB-000098',
    "Trickledown 'economic religion' was Jim Jones without the violence: ClownBinge reviews the data of American economic conditions after republican and democratic administrations.",
    'trickledown-economic-religion-jim-jones-republican-democratic-economic-record',
    "The empirical record of GDP growth, job creation, wage gains, and deficit accumulation across Republican and Democratic administrations does not support the theological claim that tax cuts for the wealthy produce broad prosperity. The data is public. The comparison is direct. The conclusions are uncomfortable only if you invested belief rather than evidence.",
    body,
    'money_and_power',
    verifiedSource,
    false,
    ['money_and_power','economics','trickle-down','republican','democratic','nerd-out','academic','how_it_works'],
    'published',
    new Date('2026-04-01T14:00:00.000Z'),
    0, 0, false, false, true, false, true
  ]
);

console.log('CB-000098 inserted:', result.rows[0].case_number);
await pool.end();
