// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo-variants/LoraItalic.tsx": () => import("../components/mockups/logo-variants/LoraItalic.tsx"),
  "./components/mockups/logo-variants/MontserratCaps.tsx": () => import("../components/mockups/logo-variants/MontserratCaps.tsx"),
  "./components/mockups/logo-variants/PlayfairLower.tsx": () => import("../components/mockups/logo-variants/PlayfairLower.tsx"),
  "./components/mockups/logo-variants/SpaceGrotesk.tsx": () => import("../components/mockups/logo-variants/SpaceGrotesk.tsx")
};
