import { useState, useRef } from "react";
import { useLocation } from "wouter";
import { Upload, FileText, CheckCircle2, AlertCircle, Info, X, Loader2, ChevronDown, ChevronUp, ArrowLeft, ExternalLink } from "lucide-react";

// ── Constants ──────────────────────────────────────────────────────────────────

const VALID_CATEGORIES = [
  "anti_racist_heroes", "censorship", "disarming_hate", "founders_pen",
  "global_south", "health_and_healing", "how_it_works", "investigations",
  "law_and_justice", "money_and_power", "native_and_first_nations", "nerd_out",
  "religion", "self_owned", "technology", "us_constitution", "us_history",
  "war_and_inhumanity", "women_and_girls",
] as const;

const SUBJECT_TYPE_TAGS = [
  "federal_elected", "state_elected", "religious_leader", "corporate_leader",
  "media_figure", "historical_figure", "institution", "think_tank",
];

const ERA_TAGS = [
  "colonial_era", "founding_era", "antebellum", "civil_war_reconstruction",
  "gilded_age", "progressive_era", "depression_wwii", "postwar",
  "civil_rights_era", "modern", "contemporary",
];

const TOPICAL_TAGS = [
  "congressional_record", "supreme_court", "bill_of_rights", "fec_records",
  "irs_990", "sec_filing", "court_record", "patent_record", "treaty",
  "executive_order", "federal_budget", "voting_rights", "civil_rights",
  "immigration", "labor", "healthcare", "environment", "education",
  "military", "science_medicine", "music_culture", "sports",
];

const PARTY_TAGS = ["republican", "democrat", "independent"];
const ALL_KNOWN_TAGS = [...SUBJECT_TYPE_TAGS, ...ERA_TAGS, ...TOPICAL_TAGS, ...PARTY_TAGS];

const PROHIBITED_ALL = [
  "because he", "because she", "despite", "hypocrite", "liar", "corrupt",
  "deliberately", "intentionally", "knew that", "secretly", "in order to deceive",
  "admitted to", "exposes", "proves", "reveals", "admits", "caught", "finally",
  "shockingly", "remarkably", "bombshell", "stunning", "outrageous",
  "true colors", "real agenda", "what he actually believes",
  "what she actually believes", "the truth about", "couldn't hide",
];

// ── Types ──────────────────────────────────────────────────────────────────────

interface ArticleInput {
  title?: string;
  slug?: string;
  teaser?: string;
  body?: string;
  category?: string;
  subjectName?: string;
  subjectTitle?: string;
  subjectParty?: string | null;
  verifiedSource?: string;
  selfOwnScore?: number | null;
  tags?: string[];
  dateOfIncident?: string;
  publishedAt?: string;
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: string;
  twitterCard?: string;
  wordCount?: number;
  readingTimeMinutes?: number;
  lastVerified?: string;
  schemaType?: string;
  authorName?: string;
  keywords?: string[];
  apaReferences?: string;
  primarySourceCount?: number;
  primarySourceTypes?: string[];
  pillar?: number;
  evScore?: number;
  clusterTag?: string;
  relatedArticles?: string[];
  updateHistory?: Array<{ date: string; note: string }>;
  seriesName?: string;
  seriesSequence?: string;
  seriesThesis?: string;
}

interface ValidationItem { field: string; message: string; }
interface AutoGenField { field: string; value: string; }
interface ValidationResult {
  errors: ValidationItem[];
  warnings: ValidationItem[];
  autoGenerated: AutoGenField[];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}

function countWords(text: string): number {
  const t = stripHtml(text).trim();
  return t.length === 0 ? 0 : t.split(/\s+/).length;
}

function countLiItems(html: string): number {
  return (html.match(/<li[\s>]/gi) || []).length;
}

function fmtCategory(cat: string): string {
  return cat.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function fmtDate(iso: string): string {
  try { return new Date(iso).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }); }
  catch { return iso; }
}

function authHeaders(): Record<string, string> {
  const h: Record<string, string> = { "Content-Type": "application/json" };
  const t = sessionStorage.getItem("metricadia_token");
  if (t) h["X-Metricadia-Token"] = t;
  return h;
}

// ── Validation (Spec Sections 5.1–5.5) ────────────────────────────────────────

function validateArticle(data: ArticleInput): ValidationResult {
  const errors: ValidationItem[] = [];
  const warnings: ValidationItem[] = [];
  const autoGenerated: AutoGenField[] = [];

  // 5.1 Required fields
  const requiredStr: Array<keyof ArticleInput> = [
    "title", "slug", "teaser", "body", "category", "subjectName",
    "subjectTitle", "verifiedSource", "metaTitle", "metaDescription",
    "apaReferences", "dateOfIncident", "publishedAt",
  ];
  for (const f of requiredStr) {
    const v = data[f];
    if (v === undefined || v === null || v === "") {
      errors.push({ field: f, message: `"${f}" is required but missing or empty.` });
    }
  }
  if (!data.tags || data.tags.length === 0) {
    errors.push({ field: "tags", message: `"tags" is required.` });
  }

  if (data.slug && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug)) {
    errors.push({ field: "slug", message: "Slug must be lowercase letters, numbers, and hyphens only (no leading/trailing hyphens)." });
  }

  if (data.category && !(VALID_CATEGORIES as readonly string[]).includes(data.category)) {
    errors.push({ field: "category", message: `"${data.category}" is not a valid category. Valid values: ${[...VALID_CATEGORIES].join(", ")}` });
  }

  if (data.tags && data.tags.length > 0) {
    if (data.tags.length < 3 || data.tags.length > 8) {
      errors.push({ field: "tags", message: `Tags must contain 3–8 items. Found: ${data.tags.length}.` });
    }
    const subjectTags = data.tags.filter((t) => SUBJECT_TYPE_TAGS.includes(t));
    if (subjectTags.length !== 1) {
      errors.push({ field: "tags", message: `Exactly one Subject Type tag required (found ${subjectTags.length}: ${subjectTags.join(", ") || "none"}).` });
    }
    const eraTags = data.tags.filter((t) => ERA_TAGS.includes(t));
    if (eraTags.length !== 1) {
      errors.push({ field: "tags", message: `Exactly one Era tag required (found ${eraTags.length}: ${eraTags.join(", ") || "none"}).` });
    }
    const unknown = data.tags.filter((t) => !ALL_KNOWN_TAGS.includes(t));
    if (unknown.length > 0) {
      warnings.push({ field: "tags", message: `Unrecognized tags — confirm before publishing: ${unknown.join(", ")}` });
    }
  }

  if (data.dateOfIncident && !/^\d{4}-\d{2}-\d{2}$/.test(data.dateOfIncident)) {
    errors.push({ field: "dateOfIncident", message: "Must be YYYY-MM-DD." });
  }

  if (data.publishedAt && isNaN(new Date(data.publishedAt).getTime())) {
    errors.push({ field: "publishedAt", message: "Must be a valid ISO 8601 datetime." });
  }

  if (data.body && !/<p[\s>]/i.test(data.body)) {
    errors.push({ field: "body", message: "Body must contain at least one <p> tag." });
  }

  if (data.metaTitle && data.metaTitle.length > 60) {
    errors.push({ field: "metaTitle", message: `metaTitle is ${data.metaTitle.length} chars — maximum 60.` });
  }

  if (data.metaDescription && data.metaDescription.length > 160) {
    errors.push({ field: "metaDescription", message: `metaDescription is ${data.metaDescription.length} chars — maximum 160.` });
  }

  if (data.selfOwnScore !== undefined && data.selfOwnScore !== null) {
    if (!Number.isInteger(data.selfOwnScore) || data.selfOwnScore < 1 || data.selfOwnScore > 10) {
      errors.push({ field: "selfOwnScore", message: "selfOwnScore must be integer 1–10 or null." });
    }
  }

  if (data.pillar !== undefined && data.pillar !== null) {
    if (!Number.isInteger(data.pillar) || data.pillar < 1 || data.pillar > 7) {
      errors.push({ field: "pillar", message: "pillar must be integer 1–7 or absent." });
    }
  }

  // 5.2 Prohibited language (case-insensitive substring)
  const scanText = `${data.title || ""} ${stripHtml(data.body || "")}`.toLowerCase();
  for (const phrase of PROHIBITED_ALL) {
    if (scanText.includes(phrase.toLowerCase())) {
      errors.push({ field: "body/title", message: `Prohibited language: "${phrase}" — rephrase as documented fact.` });
    }
  }

  // 5.3 Factoid tag check (warnings)
  if (data.body) {
    const factoids = [...data.body.matchAll(/<a[^>]+class=["'][^"']*cb-factoid[^"']*["'][^>]*>/gi)];
    for (const m of factoids) {
      const tag = m[0];
      if (!/href=["'][^"']+["']/i.test(tag)) {
        warnings.push({ field: "body", message: "A cb-factoid tag is missing href." });
      } else {
        const hm = tag.match(/href=["']([^"']*)["']/i);
        if (hm && !hm[1].startsWith("https://")) {
          warnings.push({ field: "body", message: `cb-factoid href must begin with https://: "${hm[1]}"` });
        }
      }
      if (!/data-title=["'][^"']*["']/i.test(tag)) {
        warnings.push({ field: "body", message: "A cb-factoid tag is missing data-title." });
      }
      const sm = tag.match(/data-summary=["']([^"']*)["']/i);
      if (!sm) {
        warnings.push({ field: "body", message: "A cb-factoid tag is missing data-summary." });
      } else if (sm[1].length < 50) {
        warnings.push({ field: "body", message: `A cb-factoid data-summary is ${sm[1].length} chars — minimum 50 required.` });
      }
    }
  }

  // 5.4 Word count
  const wc = countWords(data.body || "");
  if (wc > 0 && wc < 1500) warnings.push({ field: "wordCount", message: `Word count ${wc} is below the 1,500 minimum. (Info only)` });
  if (wc > 5000) warnings.push({ field: "wordCount", message: `Word count ${wc} exceeds the 5,000 maximum. (Info only)` });

  // 5.5 APA references
  const liCount = countLiItems(data.apaReferences || "");
  if (liCount < 3) warnings.push({ field: "apaReferences", message: `Found ${liCount} <li> item(s) in apaReferences — minimum 3 recommended.` });
  if (data.primarySourceCount !== undefined && data.primarySourceCount !== liCount) {
    warnings.push({ field: "primarySourceCount", message: `primarySourceCount (${data.primarySourceCount}) does not match <li> count in apaReferences (${liCount}).` });
  }

  // Section 6 — auto-generated fields
  if (!data.canonicalUrl) autoGenerated.push({ field: "canonicalUrl", value: `https://clownbinge.com/articles/${data.slug || ""}` });
  if (!data.ogTitle) autoGenerated.push({ field: "ogTitle", value: data.metaTitle || "" });
  if (!data.ogDescription) autoGenerated.push({ field: "ogDescription", value: data.metaDescription || "" });
  if (!data.twitterCard) autoGenerated.push({ field: "twitterCard", value: "summary_large_image" });
  autoGenerated.push({ field: "wordCount", value: String(wc) });
  autoGenerated.push({ field: "readingTimeMinutes", value: String(Math.ceil(wc / 238)) });
  if (!data.lastVerified && data.publishedAt) autoGenerated.push({ field: "lastVerified", value: data.publishedAt.split("T")[0] });
  if (!data.schemaType) autoGenerated.push({ field: "schemaType", value: "NewsArticle" });
  if (!data.authorName) autoGenerated.push({ field: "authorName", value: "ClownBinge Staff" });
  autoGenerated.push({ field: "primarySourceCount", value: String(liCount) });

  return { errors, warnings, autoGenerated };
}

// ── Auto-enrich (Section 6 + 7) ───────────────────────────────────────────────

function enrichArticle(data: ArticleInput): ArticleInput & {
  canonicalUrl: string; ogTitle: string; ogDescription: string;
  twitterCard: string; wordCount: number; readingTimeMinutes: number;
  lastVerified: string; schemaType: string; authorName: string;
  primarySourceCount: number; schemaMarkup: object;
} {
  const wc = countWords(data.body || "");
  const canonicalUrl = data.canonicalUrl || `https://clownbinge.com/articles/${data.slug || ""}`;
  const ogTitle = data.ogTitle || data.metaTitle || "";
  const ogDescription = data.ogDescription || data.metaDescription || "";
  const twitterCard = data.twitterCard || "summary_large_image";
  const readingTimeMinutes = Math.ceil(wc / 238);
  const lastVerified = data.lastVerified || (data.publishedAt ? data.publishedAt.split("T")[0] : new Date().toISOString().split("T")[0]);
  const schemaType = data.schemaType || "NewsArticle";
  const authorName = data.authorName || "ClownBinge Staff";
  const primarySourceCount = data.primarySourceCount ?? countLiItems(data.apaReferences || "");

  const jsonLd: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": schemaType,
    headline: data.metaTitle,
    description: data.metaDescription,
    author: { "@type": "Organization", name: authorName, url: "https://clownbinge.com" },
    publisher: {
      "@type": "Organization", name: "ClownBinge", url: "https://clownbinge.com",
      logo: { "@type": "ImageObject", url: "https://clownbinge.com/logo.png" },
    },
    datePublished: data.publishedAt,
    dateModified: lastVerified,
    mainEntityOfPage: { "@type": "WebPage", "@id": canonicalUrl },
    keywords: (data.keywords || []).join(", "),
    articleSection: data.category,
  };
  if (data.ogImage) jsonLd.image = { "@type": "ImageObject", url: data.ogImage };

  return {
    ...data, canonicalUrl, ogTitle, ogDescription, twitterCard,
    wordCount: wc, readingTimeMinutes, lastVerified, schemaType,
    authorName, primarySourceCount, schemaMarkup: jsonLd,
  };
}

// ── Component ──────────────────────────────────────────────────────────────────

const NAV = { background: "#08122E", color: "#C9A227" };
const PARCHMENT = "#F2E8D4";
const NAVY = "#08122E";
const GOLD = "#C9A227";

export default function PublishWizard() {
  const [, setLocation] = useLocation();

  const isAdmin =
    sessionStorage.getItem("metricadia_authenticated") === "true" ||
    sessionStorage.getItem("metricadia_token") !== null;

  if (!isAdmin) {
    setLocation("/Kemet8");
    return null;
  }

  const [jsonText, setJsonText] = useState("");
  const [parseError, setParseError] = useState<string | null>(null);
  const [validation, setValidation] = useState<ValidationResult | null>(null);
  const [enriched, setEnriched] = useState<ReturnType<typeof enrichArticle> | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [publishState, setPublishState] = useState<"idle" | "publishing" | "success" | "error">("idle");
  const [publishError, setPublishError] = useState<string | null>(null);
  const [successData, setSuccessData] = useState<{ caseNumber: string; url: string } | null>(null);
  const [seoOpen, setSeoOpen] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => setJsonText(ev.target?.result as string ?? "");
    reader.readAsText(file);
    e.target.value = "";
  };

  const handleValidate = () => {
    setShowPreview(false);
    setPublishState("idle");
    setPublishError(null);
    setSuccessData(null);
    let parsed: ArticleInput;
    try {
      parsed = JSON.parse(jsonText);
    } catch (err: unknown) {
      setParseError(`JSON parse error: ${err instanceof Error ? err.message : String(err)}`);
      setValidation(null);
      setEnriched(null);
      return;
    }
    setParseError(null);
    const result = validateArticle(parsed);
    setValidation(result);
    setEnriched(result.errors.length === 0 ? enrichArticle(parsed) : null);
  };

  const handleClear = () => {
    setJsonText("");
    setParseError(null);
    setValidation(null);
    setEnriched(null);
    setShowPreview(false);
    setPublishState("idle");
    setPublishError(null);
    setSuccessData(null);
  };

  const handlePublish = async () => {
    if (!enriched) return;
    setShowConfirm(false);
    setPublishState("publishing");
    setPublishError(null);
    try {
      const res = await fetch("/api/wizard/publish", {
        method: "POST",
        headers: authHeaders(),
        credentials: "include",
        body: JSON.stringify(enriched),
      });
      const data = await res.json();
      if (!res.ok || !data.ok) {
        setPublishState("error");
        setPublishError(data.error || "Unknown server error.");
      } else {
        setPublishState("success");
        setSuccessData({ caseNumber: data.caseNumber, url: data.url });
        setJsonText("");
        setValidation(null);
        setEnriched(null);
        setShowPreview(false);
      }
    } catch (err: unknown) {
      setPublishState("error");
      setPublishError(err instanceof Error ? err.message : String(err));
    }
  };

  const hasErrors = (validation?.errors.length ?? 0) > 0;
  const hasWarnings = (validation?.warnings.length ?? 0) > 0;

  return (
    <div style={{ minHeight: "100vh", background: PARCHMENT, fontFamily: "'Inter', sans-serif" }}>
      {/* Header */}
      <div style={{ ...NAV, padding: "14px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <button
            onClick={() => setLocation("/Kemet8")}
            style={{ background: "transparent", border: "none", color: GOLD, cursor: "pointer", display: "flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 700, letterSpacing: "0.12em" }}
          >
            <ArrowLeft size={13} /> BACK TO ADMIN
          </button>
          <span style={{ color: "rgba(201,162,39,0.3)" }}>|</span>
          <span style={{ color: GOLD, fontWeight: 700, fontSize: 11, letterSpacing: "0.18em" }}>ARTICLE UPLOAD WIZARD</span>
        </div>
        <span style={{ color: "rgba(255,255,255,0.3)", fontSize: 10, letterSpacing: "0.1em" }}>METRICADIA BRAIN v1.0</span>
      </div>

      {/* Success banner */}
      {publishState === "success" && successData && (
        <div style={{ background: "#14532d", color: "#86efac", padding: "16px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <CheckCircle2 size={18} />
            <span style={{ fontWeight: 700 }}>Published {successData.caseNumber}</span>
            <span style={{ opacity: 0.7 }}>— Article is live on ClownBinge.</span>
          </div>
          <a href={successData.url} target="_blank" rel="noopener noreferrer" style={{ color: "#86efac", display: "flex", alignItems: "center", gap: 4, fontSize: 12 }}>
            View live <ExternalLink size={12} />
          </a>
        </div>
      )}

      {/* Error banner */}
      {publishState === "error" && publishError && (
        <div style={{ background: "#450a0a", color: "#fca5a5", padding: "12px 32px", display: "flex", alignItems: "center", gap: 10 }}>
          <AlertCircle size={16} />
          <span style={{ fontWeight: 700 }}>Publish failed:</span> {publishError}
        </div>
      )}

      {/* Two-panel layout */}
      <div style={{ display: "flex", minHeight: "calc(100vh - 54px)" }}>

        {/* LEFT — 40% JSON input */}
        <div style={{ width: "40%", borderRight: `2px solid ${GOLD}`, padding: "28px 28px", display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ borderBottom: `1px solid rgba(201,162,39,0.4)`, paddingBottom: 10, marginBottom: 4 }}>
            <div style={{ fontWeight: 700, fontSize: 11, letterSpacing: "0.18em", color: NAVY }}>JSON INPUT</div>
            <div style={{ fontSize: 10, color: "rgba(8,18,46,0.5)", marginTop: 2, letterSpacing: "0.08em" }}>Paste article JSON or upload a .json file</div>
          </div>

          <textarea
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
            placeholder='{\n  "title": "...",\n  "slug": "...",\n  ...\n}'
            style={{
              flex: 1, minHeight: 480, resize: "vertical", fontFamily: "'Courier New', monospace",
              fontSize: 12, lineHeight: 1.6, padding: 14, border: `1.5px solid rgba(8,18,46,0.2)`,
              borderRadius: 4, background: "#fff", color: NAVY, outline: "none",
            }}
          />

          {parseError && (
            <div style={{ background: "#450a0a", color: "#fca5a5", padding: "8px 12px", borderRadius: 4, fontSize: 12 }}>
              {parseError}
            </div>
          )}

          {/* File upload */}
          <input ref={fileRef} type="file" accept=".json" style={{ display: "none" }} onChange={handleFileUpload} />
          <button
            onClick={() => fileRef.current?.click()}
            style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "9px 0", background: "transparent", border: `1.5px solid ${NAVY}`, color: NAVY, fontWeight: 700, fontSize: 11, letterSpacing: "0.14em", cursor: "pointer", borderRadius: 3 }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = NAVY; (e.currentTarget as HTMLButtonElement).style.color = GOLD; }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "transparent"; (e.currentTarget as HTMLButtonElement).style.color = NAVY; }}
          >
            <FileText size={13} /> UPLOAD .JSON FILE
          </button>

          <div style={{ display: "flex", gap: 10 }}>
            <button
              onClick={handleValidate}
              disabled={!jsonText.trim()}
              style={{ flex: 1, padding: "11px 0", background: jsonText.trim() ? NAVY : "rgba(8,18,46,0.3)", color: GOLD, fontWeight: 700, fontSize: 11, letterSpacing: "0.15em", border: "none", cursor: jsonText.trim() ? "pointer" : "not-allowed", borderRadius: 3 }}
            >
              VALIDATE
            </button>
            <button
              onClick={handleClear}
              style={{ padding: "11px 20px", background: "transparent", border: `1.5px solid rgba(8,18,46,0.3)`, color: "rgba(8,18,46,0.5)", fontWeight: 600, fontSize: 11, cursor: "pointer", borderRadius: 3 }}
            >
              CLEAR
            </button>
          </div>
        </div>

        {/* RIGHT — 60% output */}
        <div style={{ width: "60%", padding: "28px 32px", overflowY: "auto" }}>

          {!validation && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: 300, gap: 12, color: "rgba(8,18,46,0.35)" }}>
              <Upload size={36} />
              <span style={{ fontSize: 12, letterSpacing: "0.1em", fontWeight: 600 }}>PASTE JSON AND CLICK VALIDATE</span>
            </div>
          )}

          {validation && (
            <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

              {/* ERRORS */}
              {validation.errors.length > 0 && (
                <section>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, paddingBottom: 6, borderBottom: "1px solid #fca5a5" }}>
                    <AlertCircle size={15} color="#dc2626" />
                    <span style={{ fontWeight: 700, fontSize: 11, letterSpacing: "0.16em", color: "#dc2626" }}>ERRORS — {validation.errors.length} (blocks publish)</span>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {validation.errors.map((e, i) => (
                      <div key={i} style={{ background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 4, padding: "8px 12px" }}>
                        <span style={{ fontWeight: 700, fontSize: 11, color: "#dc2626" }}>{e.field}</span>
                        <span style={{ fontSize: 12, color: "#7f1d1d", marginLeft: 8 }}>{e.message}</span>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {/* WARNINGS */}
              {validation.warnings.length > 0 && (
                <section>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, paddingBottom: 6, borderBottom: "1px solid #fde68a" }}>
                    <AlertCircle size={15} color="#d97706" />
                    <span style={{ fontWeight: 700, fontSize: 11, letterSpacing: "0.16em", color: "#d97706" }}>WARNINGS — {validation.warnings.length} (publish with confirmation)</span>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {validation.warnings.map((w, i) => (
                      <div key={i} style={{ background: "#fffbeb", border: "1px solid #fde68a", borderRadius: 4, padding: "8px 12px" }}>
                        <span style={{ fontWeight: 700, fontSize: 11, color: "#d97706" }}>{w.field}</span>
                        <span style={{ fontSize: 12, color: "#78350f", marginLeft: 8 }}>{w.message}</span>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {/* AUTO-GENERATED */}
              {validation.autoGenerated.length > 0 && (
                <section>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, paddingBottom: 6, borderBottom: "1px solid #bfdbfe" }}>
                    <Info size={15} color="#2563eb" />
                    <span style={{ fontWeight: 700, fontSize: 11, letterSpacing: "0.16em", color: "#2563eb" }}>AUTO-GENERATED — {validation.autoGenerated.length} fields</span>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
                    {validation.autoGenerated.map((a, i) => (
                      <div key={i} style={{ background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 4, padding: "6px 12px", display: "flex", gap: 8 }}>
                        <span style={{ fontWeight: 700, fontSize: 11, color: "#1d4ed8", minWidth: 160 }}>{a.field}</span>
                        <span style={{ fontSize: 11, color: "#1e3a8a", fontFamily: "'Courier New', monospace" }}>{a.value.length > 80 ? a.value.slice(0, 80) + "…" : a.value}</span>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {/* Ready to preview / fix errors message */}
              {hasErrors ? (
                <div style={{ background: "#fef2f2", border: "2px solid #fecaca", borderRadius: 4, padding: "12px 16px", display: "flex", alignItems: "center", gap: 8 }}>
                  <X size={16} color="#dc2626" />
                  <span style={{ fontWeight: 700, fontSize: 12, color: "#dc2626" }}>Fix errors before preview.</span>
                </div>
              ) : (
                <button
                  onClick={() => setShowPreview(true)}
                  style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "12px 0", background: "#14532d", color: "#86efac", fontWeight: 700, fontSize: 11, letterSpacing: "0.15em", border: "none", cursor: "pointer", borderRadius: 3 }}
                >
                  <CheckCircle2 size={14} /> READY TO PREVIEW — CLICK TO RENDER
                </button>
              )}

              {/* ARTICLE PREVIEW */}
              {!hasErrors && showPreview && enriched && (
                <div style={{ border: `2px solid ${GOLD}`, borderRadius: 4, overflow: "hidden" }}>
                  <div style={{ background: NAVY, padding: "10px 20px" }}>
                    <span style={{ color: GOLD, fontWeight: 700, fontSize: 11, letterSpacing: "0.16em" }}>ARTICLE PREVIEW</span>
                  </div>
                  <div style={{ background: "#fff", padding: "32px 36px" }}>
                    {/* Category badge */}
                    <div style={{ display: "inline-block", background: NAVY, color: GOLD, fontSize: 10, fontWeight: 700, letterSpacing: "0.14em", padding: "3px 10px", borderRadius: 2, marginBottom: 14 }}>
                      {fmtCategory(enriched.category || "")}
                    </div>

                    {/* Title */}
                    <h1 style={{ fontFamily: "Georgia, serif", fontSize: 26, fontWeight: 700, color: NAVY, lineHeight: 1.3, marginBottom: 14 }}>{enriched.title}</h1>

                    {/* Meta */}
                    <div style={{ display: "flex", gap: 16, fontSize: 12, color: "rgba(8,18,46,0.55)", marginBottom: 8 }}>
                      {enriched.subjectName && <span><strong>{enriched.subjectName}</strong>{enriched.subjectTitle ? `, ${enriched.subjectTitle}` : ""}</span>}
                    </div>
                    <div style={{ display: "flex", gap: 16, fontSize: 11, color: "rgba(8,18,46,0.45)", marginBottom: 20 }}>
                      {enriched.publishedAt && <span>{fmtDate(enriched.publishedAt)}</span>}
                      <span>{enriched.readingTimeMinutes} min read</span>
                      <span>{enriched.wordCount.toLocaleString()} words</span>
                    </div>

                    {/* Teaser */}
                    {enriched.teaser && (
                      <p style={{ fontFamily: "Georgia, serif", fontSize: 16, color: "rgba(8,18,46,0.7)", fontStyle: "italic", marginBottom: 20, borderLeft: `3px solid ${GOLD}`, paddingLeft: 14 }}>{enriched.teaser}</p>
                    )}

                    {/* Body */}
                    <div
                      className="article-body"
                      style={{ fontFamily: "Georgia, serif", fontSize: 15, lineHeight: 1.8, color: NAVY }}
                      dangerouslySetInnerHTML={{ __html: enriched.body || "" }}
                    />

                    {/* Primary Sources — Section 8 */}
                    {enriched.apaReferences && (
                      <div style={{ marginTop: 32, paddingTop: 24, borderTop: `1px solid rgba(8,18,46,0.15)` }}>
                        <h2 style={{ fontFamily: "Georgia, serif", fontSize: 18, fontWeight: 700, color: NAVY, marginBottom: 6 }}>Primary Sources</h2>
                        <p style={{ fontSize: 12, color: "rgba(8,18,46,0.5)", marginBottom: 14 }}>{enriched.primarySourceCount} primary source{enriched.primarySourceCount !== 1 ? "s" : ""} documented and linked.</p>
                        <div style={{ fontSize: 13, color: NAVY, lineHeight: 1.7 }} dangerouslySetInnerHTML={{ __html: enriched.apaReferences }} />
                      </div>
                    )}

                    {/* SEO Preview (collapsible) */}
                    <div style={{ marginTop: 28, border: `1px solid rgba(8,18,46,0.15)`, borderRadius: 4, overflow: "hidden" }}>
                      <button
                        onClick={() => setSeoOpen((o) => !o)}
                        style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 14px", background: "rgba(8,18,46,0.04)", border: "none", cursor: "pointer", fontWeight: 700, fontSize: 11, letterSpacing: "0.14em", color: NAVY }}
                      >
                        SEO PREVIEW {seoOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                      </button>
                      {seoOpen && (
                        <div style={{ padding: "14px 16px", display: "flex", flexDirection: "column", gap: 8, fontSize: 12 }}>
                          <div><strong>Meta Title</strong> <span style={{ color: enriched.metaTitle && enriched.metaTitle.length > 60 ? "#dc2626" : "#15803d" }}>({enriched.metaTitle?.length || 0}/60)</span><br /><span style={{ fontFamily: "monospace" }}>{enriched.metaTitle}</span></div>
                          <div><strong>Meta Description</strong> <span style={{ color: enriched.metaDescription && enriched.metaDescription.length > 160 ? "#dc2626" : "#15803d" }}>({enriched.metaDescription?.length || 0}/160)</span><br /><span style={{ fontFamily: "monospace" }}>{enriched.metaDescription}</span></div>
                          <div><strong>Canonical URL</strong><br /><span style={{ fontFamily: "monospace" }}>{enriched.canonicalUrl}</span></div>
                          <div><strong>Schema Type</strong><br /><span style={{ fontFamily: "monospace" }}>{enriched.schemaType}</span></div>
                          {enriched.keywords && enriched.keywords.length > 0 && (
                            <div><strong>Keywords</strong><br /><span style={{ fontFamily: "monospace" }}>{enriched.keywords.join(", ")}</span></div>
                          )}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Publish button */}
                  <div style={{ background: PARCHMENT, padding: "16px 24px", borderTop: `1px solid rgba(201,162,39,0.3)` }}>
                    {publishState === "publishing" ? (
                      <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 10, padding: "12px 0", color: NAVY, fontWeight: 700, fontSize: 11 }}>
                        <Loader2 size={16} className="animate-spin" /> PUBLISHING…
                      </div>
                    ) : (
                      <button
                        onClick={() => setShowConfirm(true)}
                        style={{ width: "100%", padding: "13px 0", background: NAVY, color: GOLD, fontWeight: 700, fontSize: 12, letterSpacing: "0.18em", border: "none", cursor: "pointer", borderRadius: 3 }}
                        onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = GOLD; (e.currentTarget as HTMLButtonElement).style.color = NAVY; }}
                        onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = NAVY; (e.currentTarget as HTMLButtonElement).style.color = GOLD; }}
                      >
                        PUBLISH TO CLOWNBINGE
                      </button>
                    )}
                    {hasWarnings && (
                      <p style={{ textAlign: "center", fontSize: 11, color: "#d97706", marginTop: 8, marginBottom: 0 }}>
                        {validation!.warnings.length} warning{validation!.warnings.length !== 1 ? "s" : ""} — you have reviewed and confirmed them.
                      </p>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Confirmation modal */}
      {showConfirm && enriched && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(8,18,46,0.75)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 9999 }}>
          <div style={{ background: "#fff", borderRadius: 6, width: 480, padding: 32, boxShadow: "0 20px 60px rgba(0,0,0,0.4)" }}>
            <h2 style={{ fontFamily: "Georgia, serif", fontSize: 20, fontWeight: 700, color: NAVY, marginBottom: 12 }}>Confirm Publish</h2>
            <p style={{ fontSize: 14, color: "rgba(8,18,46,0.7)", lineHeight: 1.6, marginBottom: 24 }}>
              Publishing <strong>"{enriched.title}"</strong> to ClownBinge. This cannot be undone. Confirm?
            </p>
            <div style={{ display: "flex", gap: 12 }}>
              <button
                onClick={handlePublish}
                style={{ flex: 1, padding: "12px 0", background: NAVY, color: GOLD, fontWeight: 700, fontSize: 11, letterSpacing: "0.14em", border: "none", cursor: "pointer", borderRadius: 3 }}
              >
                CONFIRM — PUBLISH NOW
              </button>
              <button
                onClick={() => setShowConfirm(false)}
                style={{ padding: "12px 20px", background: "transparent", border: `1.5px solid rgba(8,18,46,0.3)`, color: "rgba(8,18,46,0.6)", fontWeight: 600, fontSize: 11, cursor: "pointer", borderRadius: 3 }}
              >
                CANCEL
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
